project:
  type: website
  output-dir: docs

website:
  title: "mywebsite"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Assignments"
        menu:
          - ae03-gerrymander.qmd
    right:
      - icon: github
        href: https://github.com/Quinten421
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - about.qmd
      - section: "Assignments"
        contents:
          - ae03-gerrymander.qmd
format:
  html:
    theme: minty
    css: styles.css
    toc: true