{
  "hash": "20808555f372aae5261b59a3c3999569",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"AE03 - Exploring gerrymandring\"\nauthor: \"Quinten Robinson\"\ndate: \"2026-09-10\"\nformat: html\nexecute: \n  warning: false\n  message: false\n---\n\n## Getting started\n\nLoad the `tidyverse`, `usdata`, and `sjPlot` packages, and get the `gerrymander` data out of the `usdata` package. View the data using `glimpse`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(usdata)\nlibrary(sjPlot)\nlibrary(gtsummary)\n\ngerrymander <- usdata::gerrymander\n```\n:::\n\n\n## 1. Congressional districts per state\n\nWhich state has the most congressional districts? The least? How many congressional districts are there in this state? Use functions such as `table`, `tbl_summary` or `count`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(gerrymander$state)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nAK AL AR AZ CA CO CT DE FL GA HI IA ID IL IN KS KY LA MA MD ME MI MN MO MS MT \n 1  7  4  9 53  7  5  1 27 14  2  4  2 18  9  4  6  6  9  8  2 14  8  8  4  1 \nNC ND NE NH NJ NM NV NY OH OK OR PA RI SC SD TN TX UT VA VT WA WI WV WY \n13  1  3  2 12  3  4 27 16  5  5 18  2  7  1  9 36  4 11  1 10  8  3  1 \n```\n\n\n:::\n:::\n\n\nCalifornia has the highest amount of congressional districts at 53. The least is a tie between Arkansas, Vermont, Wyoming, North Dakota, South Dakota all having 1 congressional districts.\n\n## 2. Districts at the tails\n\nMake side-by-side box plots of percent of vote received by Trump in the 2016 Presidential Election by prevalence of gerrymandering. Identify any Congressional Districts that are potential outliers — points that fall well outside the whiskers of their box, meaning that district's Trump vote share was unusually high or low compared to other districts with the same gerrymandering prevalence. What information can you share about them?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander, aes(x = trump16, y=gerry)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](ae03-gerrymander_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n```{.r .cell-code}\ngerrymander |> select(district,trump16,gerry) |> filter(gerry==\"low\" & trump16<=10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  district trump16 gerry\n  <chr>      <dbl> <fct>\n1 NY-13        5.4 low  \n2 NY-15        4.9 low  \n```\n\n\n:::\n:::\n\n\nNew York districts 13 and 15 have an unnaturally low gerrymandering rate. Ny-13 had a low gerrymandering but a voting for Trump of 5.4% and Ny-15 had a low gerrymandering rate however only 4.9% of people voted for Trump. This could be cause for more investigation.\n\n## 3. Gerrymandering and flipping\n\nThis relationship can be looked at from two directions — does gerrymandering predict a 2018 flip, and does a 2018 flip predict gerrymandering? Support **both** with a visualization and summary statistics. The plot answers \"what does the mix look like within each group?\"; the table gives the exact proportions the plot is showing. Write 1-2 bullet points about what you noticed from each plot. Use specific numbers in your answer.\n\n**Direction 1:** Is a Congressional District more likely to have high prevalence of gerrymandering if a Democrat was able to flip the seat in the 2018 election? To compare the breakdown of gerrymandering prevalence within each flipped group, make sure `flip18` is on the x axis and that your percents add up to 100% within each category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander, aes(x = flip18, fill = gerry)) +\n  geom_bar(position = \"fill\")\n```\n\n::: {.cell-output-display}\n![](ae03-gerrymander_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nThe states that didn't flip had the highest ratio of gerrymandering overall.\n\n**Direction 2:** Is a Congressional District more likely to be flipped to a Democratic seat if it has high prevalence of gerrymandering, or low prevalence? Same two variables, just flipped — so now `gerry` is on the x-axis. Again, make sure your percents add up to 100% within each category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander, aes(x = gerry, fill = as.factor(flip18))) +\n  geom_bar(position = \"fill\")\n```\n\n::: {.cell-output-display}\n![](ae03-gerrymander_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nA majority of the states didn't flip seats. Especially since the rates for each gerrymander rates were fairly consistent through out the different gerrymandering weights.\n\n## 4. Gerrymandering and presidential margin\n\nUsing `mutate`, create a new variable, `margin16`, measuring how many percentage points Clinton won or lost by in each district (`clinton16 - trump16`). Does gerrymandering prevalence relate to how lopsided the 2016 presidential race was in that district? Report the min, mean, and max margin by `gerry` level, then visualize the full distribution with a violin + boxplot combo. Describe the shape, center, and spread of each group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander %>%\n  mutate(margin16 = clinton16 - trump16) %>%\n  select(gerry,clinton16,trump16,margin16) %>%\n  arrange(margin16)%>%\n  group_by(gerry) %>%\n  summarise(min_margin16 = min(margin16),\n            mean_margin16 = mean(margin16),\n            median_margin16 = median(margin16),\n            max_margin16 = max(margin16)\n            )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  gerry min_margin16 mean_margin16 median_margin16 max_margin16\n  <fct>        <dbl>         <dbl>           <dbl>        <dbl>\n1 low          -54.9          6.32           -2.05         88.9\n2 mid          -63            3.25           -1.3          82.8\n3 high         -63            1.34           -6.5          78.2\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n gerrymander %>%\n  mutate(margin16 = clinton16 - trump16) %>%\n  select(gerry,clinton16,trump16,margin16) %>%\n  arrange(margin16)%>%\n  group_by(gerry) %>% ggplot(aes(x = gerry, y = margin16)) +\n  geom_violin()+geom_boxplot()+coord_flip()\n```\n\n::: {.cell-output-display}\n![](ae03-gerrymander_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nLow gerrymandering weights had minimum value -54.9% and a max value of 88.9% when comparing Clinton voting rates to Trump for each district. The low gerrymandering districts also had a median of -2.05% and a mean of 6.32%. The low gerrymandering rate had a right skew, with a wide spread, and centered at 6.32%.\n\nMedium gerrymandering weights had minimum value -63% and a max value of 82.8% when comparing Clinton voting rates to Trump for each district. The medium gerrymandering districts also had a median of -1.3% and a mean of 3.2%. The medium gerrymandering rate had a fairly even spread, was skewed to the right, centered at 3.2%.\n\nHigh gerrymandering weights had minimum value -63% and a max value of 78.2% when comparing Clinton voting rates to Trump for each district. The high gerrymandering districts also had a median of -6.5% and a mean of 1.34%. The high gerrymandering rate had a fairly even spread, was skewed to the right, centered at 1.34%.\n",
    "supporting": [
      "ae03-gerrymander_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}